### ISSUE TITLE
oh man i git broke things

### ISSUE THREAD

**Issue by joellebegin** [joellebegin/Power-Spectra#22]
After merging my IDE is giving me a *lot* of errors I didn't have before. I think I'm going to have figure out how to hard reset to an earlier version...

**Comment by acliu** [comment]
Perfect time for something we’ll learn about this week in the PHYS 321 Coding Lab :) It won’t help directly with your current problem, but it’ll be a helpful habit to build for the future!

On Feb 10, 2020, at 5:41 PM, Joelle Begin <notifications@github.com> wrote:

﻿

After merging my IDE is giving me a lot of errors I didn't have before. I think I'm going to have figure out how to hard reset to an earlier version...

**Comment by joellebegin** [comment]
I just did it manually... not too bad; but I will learn better practices for the future!
